// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cpp_str_sort
std::vector<std::string> cpp_str_sort(std::vector<std::string> strings);
RcppExport SEXP LookR_cpp_str_sort(SEXP stringsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type strings(stringsSEXP);
    __result = Rcpp::wrap(cpp_str_sort(strings));
    return __result;
END_RCPP
}
