# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_str_sort <- function(strings) {
    .Call('LookR_cpp_str_sort', PACKAGE = 'LookR', strings)
}

